//Generated By build.js Wed Dec 12 2018 16:57:11 GMT+0800 (中国标准时间)
const abs = require("./src/abs.js");
const acos = require("./src/acos.js");
const asin = require("./src/asin.js");
const atan = require("./src/atan.js");
const ceil = require("./src/ceil.js");
const degreeToRotate = require("./src/common/degreeToRotate.js");
const devideFloat = require("./src/common/devideFloat.js");
const isFloat = require("./src/common/isFloat.js");
const rotateToDegree = require("./src/common/rotateToDegree.js");
const cos = require("./src/cos.js");
const floor = require("./src/floor.js");
const pow = require("./src/pow.js");
const round = require("./src/round.js");
const sin = require("./src/sin.js");
const sqrt = require("./src/sqrt.js");
const tan = require("./src/tan.js");

module.exports.default = module.exports = {
	abs,
	acos,
	asin,
	atan,
	ceil,
	degreeToRotate,
	devideFloat,
	isFloat,
	rotateToDegree,
	cos,
	floor,
	pow,
	round,
	sin,
	sqrt,
	tan
}